# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: TrackerSoftware.PDF-XChangePRO
PackageVersion: 10.7.5.403
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2025-10-28
Installers:
- Architecture: x86
  InstallerUrl: https://downloads.pdf-xchange.com/ProV10.x86.msi
  InstallerSha256: 2776FD809236EB50337A50767B20E24D7A7429CE0323F2BC2C25EA877D9E0B07
  ProductCode: '{43A9215E-9C78-456A-AAE7-39A35F824F13}'
  AppsAndFeaturesEntries:
  - Publisher: PDF-XChange Co Ltd.
    ProductCode: '{43A9215E-9C78-456A-AAE7-39A35F824F13}'
    UpgradeCode: '{9AC998B9-BD41-46DC-8F08-0DE2A4A1EB4D}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Tracker Software'
- Architecture: x64
  InstallerUrl: https://downloads.pdf-xchange.com/ProV10.x64.msi
  InstallerSha256: FD023BFA7E0C9B3D428793E057E63F8CDF1418F19B613BC44C6CD229D43063F7
  ProductCode: '{5E64A837-0BF1-4A77-8412-CEC1D39C86D3}'
  AppsAndFeaturesEntries:
  - Publisher: PDF-XChange Co Ltd.
    ProductCode: '{5E64A837-0BF1-4A77-8412-CEC1D39C86D3}'
    UpgradeCode: '{F363AF73-86E7-4782-87FA-F3C14FA4D395}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Tracker Software'
- Architecture: arm64
  InstallerUrl: https://downloads.pdf-xchange.com/ProV10.ARM64.msi
  InstallerSha256: 467A7FF67FDB114D50CFC4C5BB46629BCBD1FEFD842296ED20D89F08B5C41F94
  ProductCode: '{CF429994-F573-4C4C-BE12-2BECB4DBCF2C}'
  AppsAndFeaturesEntries:
  - Publisher: PDF-XChange Co Ltd.
    ProductCode: '{CF429994-F573-4C4C-BE12-2BECB4DBCF2C}'
    UpgradeCode: '{6F616659-45F6-4637-84FB-31E8C25753AB}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Tracker Software'
ManifestType: installer
ManifestVersion: 1.10.0
